.babelrc
babel.config.js
jest.config.js
package-lock.json
package.json
src/__tests__/firebase.test.js
src/__tests__/isoCodeList.test.js
src/components/BilingualTextInput.jsx
src/components/CheckBoxList.jsx
src/components/MetadataForm.jsx
src/components/Submissions.jsx
src/components/__tests__/BilingualTextInput.test.jsx
src/components/__tests__/CheckBoxList.test.jsx
src/components/__tests__/DateInput.test.jsx
src/components/__tests__/MetadataForm.test.jsx
src/components/__tests__/SelectInput.test.jsx
src/components/__tests__/Submissions.test.jsx
src/components/__tests__/Success.test.jsx
src/setupTests.js

Note: Merging this PR will break any branches that do not have unit tests.
Minimum coverages (%) are:
"branches": 80,
"functions": 90,
"lines": 100,
"statements": 90

Metadata entry form 9

---

src/components/FormComponents/MapSelect.jsx
src/components/FormComponents/SpatialTab.jsx
src/components/MetadataForm.jsx

Primary features of polygon support have been implemented.  A simpler version of this could be done for points as well.
**NOTE:** 
If there isn't a bounding box or polygon already drawn on the map, entering/changing the points in the respective fields won't instantiate a new shape to visualize them.  Should this be implemented before merging?

Polygon support

---

src/components/FormComponents/IdentificationTab.jsx
src/components/FormComponents/MapSelect.jsx
src/components/FormComponents/MetadataTab.jsx
src/isoCodeLists.js
src/utils/misc.js

- Add 'other' EOV
- Fix map select with non-decimal numbers
- other random bug fixes
Fixes #41
Fixes #39

Bug fixes and more

---

src/components/FormComponents/DistributionTab.jsx
src/components/FormComponents/MapSelect.jsx
src/components/FormComponents/PlatformTab.jsx
src/components/FormComponents/SpatialTab.jsx
src/components/MetadataForm.jsx

An attempt to clarify some of the metadata questions. Also a misc bug fix where the creation date sometimes wasn't appearing in Firebase console
Fixes #18

more explanations, misc bug fix

---

src/components/FormComponents/Contact.jsx
src/components/FormComponents/Contacts.jsx
src/components/FormComponents/SelectMultipleInput.jsx

Since our YAML schema allows multiple roles for each contact, I have added this functionality to the form as well. Adds a multi-select component that can be reused elsewhere
Fixes #47

allow multiple roles for each contact

---

src/components/FormComponents/BilingualTextInput.jsx
src/firebase.js
src/providers/UserProvider.jsx

This modifies the BIlingualTextField component to add a 'translate' button which can translate from the primary language (set by UI dropdown) 
Fixes #17

add translate button to bilingual fields, uses cloud function

---

src/components/Submissions.jsx

This PR adds a button to the saved records page so the user can duplicate a record.
Fixes #38

add ability to duplicate saved records

---

src/components/FormComponents/DateInput.jsx
src/components/FormComponents/Distribution.jsx
src/components/FormComponents/IdentificationTab.jsx

add fields

---

src/components/validate.js

Instrument is optional in the profile, looks like I had made it required

make instrument optional

---

firebase_to_xml/firebase_to_xml.py

Just a tiny change restoring the error handling to how it was before I messed with it

restoring error handling in python script to how it was

---

src/components/BaseLayout.jsx
src/components/FormComponents/EditContact.jsx
src/components/FormComponents/LastEdited.jsx
src/components/NavDrawer.jsx
src/components/Pages/Contacts.jsx
src/components/Pages/MetadataForm.jsx
src/components/Pages/NotFound.jsx
src/components/Pages/Reviewer.jsx
src/components/Pages/Submissions.jsx

There were some issues with sharing of a metadata record via URL before, this PR should fix them. 
Fixes #95

fix sharing of metadata record via URL

---

firebase_to_xml/firebase_to_xml/record_json_to_yaml.py

Looks like progress_code wasn't being set. Related to https://github.com/cioos-siooc/metadata-xml/pull/88

add missing progress_code

---

src/components/FormComponents/Contact.jsx
src/components/FormComponents/ContactTitle.jsx
src/components/FormComponents/DateInput.jsx
src/components/FormComponents/Distribution.jsx
src/components/FormComponents/MapSelect.jsx
src/components/Pages/RegionSelect.jsx
src/components/Pages/Reviewer.jsx
src/components/Pages/Submissions.jsx
src/components/Tabs/ContactTab.jsx
src/components/Tabs/DistributionTab.jsx
src/components/Tabs/IdentificationTab.jsx
src/components/Tabs/SpatialTab.jsx
src/components/Tabs/StartTab.jsx
src/components/Tabs/SubmitTab.jsx
src/regions.js
src/utils/i18nDictionaryFr.js

Fix french translation

---

src/components/FormComponents/DateInput.jsx
src/components/Tabs/IdentificationTab.jsx

Not sure if there's other places where this needs doing.  Addresses issue #100

Ensures data collection end date occurs after start date

---

src/components/FormComponents/ContactEditor.jsx
src/components/FormComponents/MapSelect.jsx
src/components/Pages/ContactsSaved.jsx
src/components/Pages/Login.jsx
src/components/Pages/RegionSelect.jsx
src/components/Pages/Submissions.jsx
src/components/Tabs/ContactTab.jsx
src/components/Tabs/IdentificationTab.jsx
src/components/Tabs/PlatformTab.jsx
src/components/Tabs/SpatialTab.jsx
src/components/Tabs/StartTab.jsx
src/components/Tabs/SubmitTab.jsx
src/regions.js
src/utils/i18nDictionaryFr.js
src/utils/validate.js

20210601 fix translations

---

src/components/Tabs/IdentificationTab.jsx

change doi label state to show a doi code instead of a doi url. (the catalog harvests doi codes only)

change doi label

---

src/components/FormComponents/ApaPreview.jsx
src/components/FormComponents/BilingualTextInput.jsx
src/components/FormComponents/CheckBoxList.jsx
src/components/FormComponents/ContactEditor.jsx
src/components/FormComponents/ContactLeftList.jsx
src/components/FormComponents/MetadataRecordListItem.jsx
src/components/FormComponents/RecordStatusIcon.jsx
src/components/FormComponents/StatusChip.jsx
src/components/Pages/MetadataForm.jsx
src/components/Pages/RegionSelect.jsx
src/components/Pages/Reviewer.jsx
src/components/Pages/Start.jsx
src/components/Pages/Submissions.jsx
src/components/Tabs/ContactTab.jsx
src/components/Tabs/IdentificationTab.jsx
src/components/Tabs/SubmitTab.jsx
src/isoCodeLists.js
src/regions.js

This PR addresses many issues, the biggest change is on the Review Submissions page, where you can now see and filter drafts from all users.
Also:
- Adds APA preview
Fixes #99
Fixes #101
Fixes #106 
Fixes #123 
Fixes #125
Fixes #130 
Fixes #133
Fixes #131

Review submissions page show drafts

---

package-lock.json
package.json
src/components/FormComponents/ApaPreview.jsx
src/components/FormComponents/BilingualTextInput.jsx
src/components/FormComponents/ContactEditor.jsx
src/components/FormComponents/Resources.jsx
src/components/Pages/Submissions.jsx
src/components/Tabs/IdentificationTab.jsx
src/providers/UserProvider.jsx
src/utils/validate.js

This PR adds form validation to a few fields 
- URLs (in contacts and resources)
- Email
- DOI
Fixes #137

Form validation

---

src/components/FormComponents/ApaPreview.jsx
src/components/FormComponents/BilingualTextInput.jsx
src/components/Pages/Submissions.jsx
src/components/Tabs/IdentificationTab.jsx
src/components/Tabs/SubmitTab.jsx
src/utils/validate.js

Missed a couple things in that first form validation PR. This adds some missing french and fixes a couple bugs

missing bilingual text, fix a console warning

---

src/regions.js

I made a new test region, not visible from the region selection page. I havent found a way to test firebase functions in the development database, this is what it will mostly be used for.

add fake "Test" region for testing

---

firebase-functions/functions/index.js
firebase-functions/functions/updates.js
src/components/Pages/MetadataForm.jsx
src/providers/UserProvider.jsx

Now XML in the WAF generates almost instantly,  instead of updating every 5 minutes

trigger XML update on saving record

---

src/components/Pages/MetadataForm.jsx
src/utils/blankRecord.js
src/utils/firebaseRecordFunctions.js

This fixes a bug where multiple new records can end up having the same UUID. I will correct the handful of records that this affected and contact the creators
Fixes #164

fix new records getting same UUID

---

src/components/Pages/Reviewer.jsx
src/components/Pages/Submissions.jsx

This fixes a couple issues - not being able to clone from the reviewer page and one of the submit buttons not working

Misc bug fixes

---

firebase-functions/functions/index.js
firebase-functions/functions/updates.js
src/components/FormComponents/TransferModal.jsx

Fix bug where transfer record wasn't causing XML to update

fix bug with transfer record

---

src/components/Tabs/SpatialTab.jsx

fix depth/height text

---

package-lock.json
package.json
src/components/FormComponents/MetadataRecordListItem.jsx
src/utils/emlTemplate.j2
src/utils/recordToEML.js

This creates a very basic Obis EML file from the metadata form, which can be used to start a metadata record in the IPT. It doesn't attempt to create a complete EML file, which would take more work

add basic EML draft creation

---

firebase_to_xml/firebase_to_xml/resources/eov.json
src/components/Tabs/IdentificationTab.jsx
src/components/Tabs/SpatialTab.jsx
src/eovs.json

This is a few updates to text that have mostly already been pushed to the website

misc text updates

---

firebase-functions/functions/dataset-name.md
firebase-functions/functions/issue.js
firebase-functions/functions/notify.js
firebase-functions/functions/package-lock.json
firebase-functions/functions/package.json

For Hakai records only (for now), creates a new issue in repo https://github.com/HakaiInstitute/metadata-review when a record is submitted.

create github issue for hakai records on submit

---

package-lock.json
package.json
src/components/FormComponents/MetadataRecordListItem.jsx
src/utils/recordToERDDAP.js

This PR moves ERDDAP snippet generation  from the repo called 'cioos-yaml-to-erddap' into this repo.
See https://github.com/cioos-siooc/cioos-yaml-to-erddap - that repo will be removed once this PR is merged.

move erddap snippet generation to browser

---

src/components/FormComponents/Resources.jsx

make resource name optionally bilingual

---

firebase_to_xml/firebase_to_xml/record_json_to_yaml.py
src/components/BaseLayout.jsx
src/components/FormComponents/ApaPreview.jsx
src/components/FormComponents/ContactEditor.jsx
src/components/FormComponents/ContactLeftList.jsx
src/components/FormComponents/ContactTitle.jsx
src/components/FormComponents/EditSavedContact.jsx
src/components/FormComponents/KeywordsInput.jsx
src/components/FormComponents/RolePicker.jsx
src/components/Tabs/ContactTab.jsx
src/isoCodeLists.js
src/utils/emlTemplate.j2
src/utils/firebaseContactFunctions.js
src/utils/recordToEML.js
src/utils/validate.js

This PR adds
- "Appear in citation" button, so that the contacts only appear in the citation if they are explicitly set that way
- Separate first name and last names into two fields, to help with citation generation
Resolves #189
Resolves #188
Resolves #172
Resolves #184

Contacts page updates

---

src/components/FormComponents/ContactEditor.jsx

orcid: can edit name & email
ror: can edit address

Made more orcid/ror fields editable

---

src/components/FormComponents/ApaPreview.jsx
src/components/Tabs/ContactTab.jsx
src/utils/emlTemplate.j2
src/utils/recordToEML.js

Made some changes and additions to the emlTemplate.j2 file and hoping that now contact organization, position and resource contact will be populated in the IPT when ingested. Also made some changes to how the DOI is mapped over but not sure if that works properly (yet).

Changes and additions to emlTemplate.j2

---

src/components/Tabs/IdentificationTab.jsx

Fixes [227](https://github.com/cioos-siooc/metadata-entry-form/issues/227)

Reworded version prompt & moved beside revision date

---

src/utils/emlTemplate.j2

PR for changes made to the emlTemplate.j2 file.

Eml template updates

---

src/components/Tabs/IdentificationTab.jsx

fix update doi by passing in region to mapping function.

fix update doi to be passed region

---

firebase_to_xml/firebase_to_xml/resources/licenses.json
src/utils/licenses.js

Added license entry per https://github.com/cioos-siooc/metadata-entry-form/issues/231

Added license for environment-climate-change-canada

---

src/eovs.json

https://github.com/cioos-siooc/metadata-entry-form/issues/247

Add Ocean Bottom Pressure to list of EOV's

---

package.json
src/components/FormComponents/Resources.jsx

debounce the list of resources correctly. I switched to the 'just-debounce-it' library as the previous one didn't work for this.

fix debounce on resouces

---

firebase_to_xml/firebase_to_xml/record_json_to_yaml.py
src/components/Pages/MetadataForm.jsx

This PR addresses the request made in issue https://github.com/cioos-siooc/metadata-entry-form/issues/256
Changes made:
Extend 'Generated from' to include full link to the metadata record.

Retrieve CIOOS Metadata form associated to a CKAN record

---

src/components/FormComponents/BilingualTextInput.jsx

used alternateTranslation, `message` isn't making it into the translation field though?

use alternateTranslation

---

.github/workflows/firebase-deploy.yaml
.github/workflows/firebase-hosting-pull-request.yml
.github/workflows/run-build-tests.yaml
src/firebase.js

Key was regenerated & authentication is broken without it

Updated firebase API key

---

.github/workflows/github-pages-deploy.yaml

Provide GH secrets to production deployment environment

Added env for google cloud to production deploy

---

src/components/Tabs/SubmitTab.jsx
src/regions.js

Improve readability of the SubmitTab component and remove redundant catalogue title entries in regions.js.

Refactor SubmitTab component and clean up regions.js
