- src/components/FormComponents/Contact.jsx
- src/components/FormComponents/ContactTab.jsx
- src/components/MetadataForm.jsx
The form was not saving dates in new forms, but was working on updating existing forms. The firebase update() function is working to store dates but the push() function isnt.
Also a couple misc bug fixes
Fixes #26
> Fix date issue, couple bug fixes

- firebase_to_xml/firebase_to_xml.py
- src/components/FormComponents/MetadataTab.jsx
This removes the option to input a naming authority for the identifier. Since the identifier is a UUID provided by the form, this PR hardcodes it to 'ca.cioos'.
Also makes 'use limitations' optional
Fixes #48
Fixes #46
> hardcode naming authority

- src/components/Reviewer.jsx
- src/components/Submissions.jsx
As discussed, adds a link on the Reviewer page to the website that lists published records for your region (in yaml/xml)
Also snuck in a small bug fix on the Saved Records page where the edit button was being displayed but the record wasn't editable
> add link to website with published metadata

- firebase_to_xml/.env
- firebase_to_xml/README.md
- firebase_to_xml/firebase_to_xml.py
This update:
- fixes the unicode output in the yaml. 
- updates the 'role' section to reflect the multiple role changes we've made
- removes the .env file to simplify making sure required fields are supplied with argparse
> fix unicode output, remove .env setup

- firebase_to_xml/firebase_to_xml/record_json_to_yaml.py
These east coast licenses were missing from the python script. Better way to manage licenses to come, perhaps these could be stored in firebase if we will be continually adding to the list.
Fixes #107, #89
> add east coast licenses

- src/components/Pages/Admin.jsx
- src/providers/UserProvider.jsx
This is a small change to how the list of admins/reviewers is stored, changes it to a comma separated string. eg:
```json
{
"permissions": {
"admins": "a@b.ca,e@f.ca,g@h.ca",
"reviewers": "e@f.ca"
}
}
```
This will make it easier to work with Firebase security rules (See #24).
This requires a small change to the database before it will work properly
> admin and reviewer switch to comma separated list

- src/components/Tabs/ContactTab.jsx
- src/components/Tabs/IdentificationTab.jsx
- src/components/Tabs/SpatialTab.jsx
- src/components/Tabs/StartTab.jsx
- src/isoCodeLists.js
This are mostly issues brought to me by @timvdstap and Metadata TT . Typos and a couple small bug fixes:
- license links not working
- height/depth clarification on spatial page
- change wording from 'profile' to 'record' for consistency
> Fix typos and small bugs

- firebase_to_xml/setup.py
fix pip install error
```
Running command git clone -q git://github.com/cioos-siooc/metadata-xml.git /tmp/pip-install-5di5gvtz/metadata-xml_c26e70b099084c6aace0b70d935c8840
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
> fix module requirements

- src/components/Tabs/IdentificationTab.jsx
- src/components/Tabs/ResourcesTab.jsx
Hey guys,
I updated to some guidance text in the identificationTab and ResourcesTab to (hopefully) help users better understand that resource URLs don't necessarily need to link to individual files, and that 'data revised' field does not need to be populated / updated for metadata.
> Updated text for the IdentificationTab and ResourcesTab

- .eslintrc
- firebase_to_xml/firebase_to_xml/record_json_to_yaml.py
- src/components/BaseLayout.jsx
- src/components/FormComponents/MetadataRecordListItem.jsx
- src/components/FormComponents/Platform.jsx
- src/components/FormComponents/SimpleModal.jsx
- src/components/Pages/MetadataForm.jsx
- src/components/Pages/Published.jsx
- src/components/Pages/Reviewer.jsx
- src/components/Pages/Submissions.jsx
- src/components/Tabs/PlatformTab.jsx
- src/platforms.json
- src/utils/blankRecord.js
- src/utils/firebaseRecordFunctions.js
- src/utils/misc.js
- src/utils/recordToEML.js
- src/utils/validate.js
This PR adds a dropdown to the Platform page where users can enter the platform using [NERC L06 Vocabulary](http://vocab.nerc.ac.uk/collection/L06/current/)
This will simplify entering platform information for a lot of datasets. I removed the requirement of needing an instrument if there is a platform, as I think this way we will get more people entering platform information even if they don't have instrument information. Now just an L06 platform type and unique platform identifier is all that's required
Also increases size of tooltip (mouse-over) text throughout the site
Relates to #179
> platform selection using NERC L06 dropdown

- firebase_to_xml/firebase_to_xml/record_json_to_yaml.py
- src/components/Pages/Admin.jsx
- src/components/Pages/MetadataForm.jsx
- src/components/Tabs/IdentificationTab.jsx
- src/regions.js
- src/utils/firebaseRecordFunctions.js
This PR adds project selection on the Data identification page. Each region can configure their own project list in the Admin page. If the region doesn't list any projects, the question won't be asked. 
This feature is aready implemented in [the metadata-xml repo](https://github.com/cioos-siooc/metadata-xml/)
Fixes #191
> add projects option

- firebase-functions/functions/issue.js
This is related to #245 
The generated issue body fails to provide a working link when a trailing `_` is present.
See https://github.com/HakaiInstitute/metadata-review/issues/66 for an example
> Surround firebase-functions-issue generated body url by < >

- src/components/Tabs/IdentificationTab.jsx
- src/utils/validate.js
There were two functions to validate DOI resulting in different behaviour in different areas of the form. This PR makes DOIs required to be valid URLs everywhere
> fix doi validation

- src/components/BaseLayout.jsx
This PR solves issue: https://github.com/cioos-siooc/metadata-entry-form/issues/96
Updated MUI theme to make disabled input text, checkboxes and labels a darker grey, to make the values easier to read.
> Change disabled components to darker grey

- src/__testData__/expectedDataCiteStructure.js
- src/__testData__/mockMetadataRecord.js
- src/utils/recordToDataCite.js
This PR solves the issue: https://github.com/cioos-siooc/metadata-entry-form/issues/270
* added version to datacite json if it exists in the metadata record
* added fundingReferences array for any organizations selected as 'Funder'
* fixed test files so the `recordToDataCite` test passes
> 270 Missing fields when drafting DataCite DOI

- src/components/FormComponents/ApaPreview.jsx
- src/components/FormComponents/DateInput.jsx
- src/components/__tests__/DateInput.test.jsx
- src/utils/recordToDataCite.js
This PR fixes the discrepancy outlined in https://github.com/cioos-siooc/metadata-entry-form/issues/295
Updated `recordToDataCite` mapping function to set publicationYear to dateRevised if it exists, otherwise use datePublished.
Updated `generateCitation` function to check for dateRevised before datePublished.
> Fix Discrepancy for publicationYear

- .github/workflows/firebase-deploy.yaml
- README.md
- firebase-functions/functions/datacite.js
- firebase-functions/functions/issue.js
- firebase-functions/functions/notify.js
- firebase-functions/functions/translate.js
This PR addresses the issue https://github.com/cioos-siooc/metadata-entry-form/issues/309, related to the lack of checks for necessary Authentication environment variables, which was leading to deployment issues and runtime errors. 
- **Introduction of Parameterized Configuration**: The CLI will prompt for parameter values during deployment if they are not preset. This helps prevent functions from being deployed with missing credentials if maintainers deploy from their local machine.
- **Improvements to `firebase-deploy` GitHub Actions workflow **: Automated creation of a virtual `.env` file as part of the deployment workflow to ensure all required environment variables are set.
- **Added Firebase Functions Deployment and Config Process in README**: Modified the README with instructions …
> 309 Enhancement of Environment Variable Handling

- src/components/Tabs/ContactTab.jsx
- src/utils/validate.js
These changes address the inconsistent text/labels noted in issue: https://github.com/cioos-siooc/metadata-entry-form/issues/249
On submit tab changed "Data Contact" and "Metadata Contact" to "Data Owner" and "Metadata Custodian" to match the text in Contact Tab.
Added "One contact can occupy multiple roles" on Contact tab, and in Contact Error warning on Submit Tab.
> fix contact discrepancy and clarify one contact can occupy multiple roles

- .github/workflows/firebase-deploy.yaml
The following workflow failed:
- name: Deploy to Firebase
uses: w9jds/firebase-action@master
v13.4.1 was released 17 hours ago so likely there is a bug
using v13.2.1 for now.
> use previous firebase deploy action version

- firebase-functions/functions/notify.js
This PR addresses https://github.com/cioos-siooc/metadata-entry-form/issues/332
Changes:
The database structure was recently updated to store permissions under an `admin` node. 
To fix the bug in the mentioned issue, database queries in the firebase functions needed to be updated to reflect the recent changes to the database structure.
> fix queries in notifyReviewer and notifyUser to access permissions

- firebase-functions/database.rules.json
- src/providers/UserProvider.jsx
This PR fixes the bug noted in https://github.com/cioos-siooc/metadata-entry-form/issues/331
Due to the recent restructure of admin/permissions in the database, the `loggedIn` state was not being updated for non-admin users.
The fix sets the `loggedIn` state for authenticated users before checking further permissions.
Also needed to fix Firebase rules to allow read on permissions for all authenticated users.
> Fix loggedIn state not set for non-admin users

- src/components/FormComponents/ContactEditor.jsx
fix https://github.com/cioos-siooc/metadata-entry-form/issues/336
populate ror immedeitly if only one result is returned. use exact matching qhen searching for organizations so that spaces are handled correclty
> 336 ROR search field doesn't always populate ROR URL
